theme: jekyll-theme-slate

title: "COMP256 - Computing Abstractions"
description: "A broad examination of the role and evolution of the abstraction hierarchies that enable the construction of complex computing systems."
