theme: jekyll-theme-slate

title: "COMP 491/492"
description: "Dickinson College Computer Science Senior Seminar"

hide_first_title: true
show_downloads: false
buttons:
  zip_hide: true
  tar_hide: true
  github_hide: true
